install: travis_wait 30 mvn install

language: java

sudo: required

before_install:
 - chmod +x gradlew
 - chmod +x gradle/buildThroughTravis.sh

install: true

script:
  - gradle/buildThroughTravis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:

  directories:

  - $HOME/.m2

  - $HOME/.gradle

