install: travis_wait 150 mvn install

language: java

sudo: required

addons:
  sonarcloud:
    organization: drip
    token:
      secure: db688c873006dda2e5380fc8fc1774343568df0a

before_install:
 - chmod +x gradlew
 - chmod +x gradle/buildThroughTravis.sh

install: true

script:
  - gradle/buildThroughTravis.sh
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:

  directories:

  - $HOME/.m2

  - $HOME/.gradle

