install: travis_wait 150 mvn install

language: java

sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gl7SQw9T2vIvSpNs3/80GnC4HuHtqqjU5MCZUio31JV3U6wELsPs7BrULs4+iq6TtsVPLOt1xIwH5RsOhyxHrkyGQRImake4EkOPLx9WwBN1QvJpD5TjBxnioUJBvM8N4BNM1CqU8UpQflH7X7BrAvk3A83mEhJSUiPt2ruViUaa5OJAeZuOjWhmdBQtXbsRv9v6S746+lMyc0iyIvXc99ezRd6iG5rjj/iUNEng2LHJRnf2BqO2tPJm1p3rJ3/LxQpxM8HXSgTzac/qlLhdrhVqvI67+1Cz0xxyAqwnfPFxscLkYB48giXTdsyv5aZ2l7CUge9tHHv1u5vIchFPH7Mvx2mm4v+gZ5mej+h/3d8dudQKvuLYqdNAc5oetYJozjDuobspsAtum3c91erERPLNoTNsnAvXuYskom1r+qlRVnnWcLK9OONWNUqiHHxDP6CGOmULNdNmPNqIuoqqd1H0VyaefAGfBeIfP8DZ/O2e1J4nrppkhn9SBR0wK9J2x7fpzjazVuucCJtWUlBUjSvinu7rRoeGe1GYUDFS+4gLpu+M+0vCS/T3h/vN//v3YWegmYEfwBMal5JTOvbmANcOCIidGWWtydK2VtjQqXSCzwly07KGPuP/G5FcJZiYu3ivY8bcbVkB5VI/mcwR60VRwtHqGkJQwPGx9DMJVak="
   - COVERALLS_REPO_TOKEN=EgNJe2CkG0qwOyJl5mdy1aiJ8LKuqbWjU
   - CI_NAME=travis-ci

before_install:
 - chmod +x gradlew
 - chmod +x gradle/buildThroughTravis.sh
 - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "lakshmiDRIP/DROP"
      description: "Build submitted via Travis CI"
    notification_email: lakshmimv7977@gmail.com
    build_command_prepend: "/gradlew clean"
    build_command:   "./gradlew compileJava"
    branch_pattern: master

install: true

script:
  - gradle/buildThroughTravis.sh
   - ./gradlew jacocoTestReport coveralls

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:

  directories:

  - $HOME/.m2

  - $HOME/.gradle
