install: travis_wait 150 mvn install

language: java

sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - COVERALLS_REPO_TOKEN=EgNJe2CkG0qwOyJl5mdy1aiJ8LKuqbWjU

before_install:
 - chmod +x gradlew
 - chmod +x gradle/buildThroughTravis.sh

install: true

script:
  - gradle/buildThroughTravis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
   - ./gradlew jacocoTestReport coveralls

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
