version: "{build}"

branches:
  only:
    - master

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.gradle

build_script:
  - gradlew.bat build

test_script:
  - gradlew.bat test

matrix:
  fast_finish: true
